package repository

import (
	"context"
	"errors"
	"fmt"

	"ecotracker/internal/domain"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type AuthRepository struct {
	db *pgxpool.Pool
}

func NewAuthRepository(db *pgxpool.Pool) *AuthRepository {
	return &AuthRepository{db: db}
}

// CreateProfile inserts a new profile row (UUID generated by DB via gen_random_uuid())
func (r *AuthRepository) CreateProfile(ctx context.Context, p *domain.Profile) error {
	query := `
		INSERT INTO profiles (id, name, email, phone, role, password_hash, total_points)
		VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, 0)
		RETURNING id, created_at, updated_at`

	err := r.db.QueryRow(ctx, query, p.Name, p.Email, p.Phone, p.Role, p.PasswordHash).
		Scan(&p.ID, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return fmt.Errorf("create profile: %w", err)
	}
	return nil
}

// GetProfileByEmail finds a profile by email address
func (r *AuthRepository) GetProfileByEmail(ctx context.Context, email string) (*domain.Profile, error) {
	query := `
		SELECT id, name, email, COALESCE(phone,''), role, total_points,
		       COALESCE(address_default,''), COALESCE(avatar_url,''),
		       password_hash, created_at, updated_at
		FROM profiles
		WHERE email = $1`

	p := &domain.Profile{}
	err := r.db.QueryRow(ctx, query, email).Scan(
		&p.ID, &p.Name, &p.Email, &p.Phone, &p.Role,
		&p.TotalPoints, &p.AddressDefault, &p.AvatarURL,
		&p.PasswordHash, &p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("get profile by email: %w", err)
	}
	return p, nil
}

// GetProfileByID finds a profile by UUID
func (r *AuthRepository) GetProfileByID(ctx context.Context, id string) (*domain.Profile, error) {
	query := `
		SELECT id, name, email, COALESCE(phone,''), role, total_points,
		       COALESCE(address_default,''), COALESCE(avatar_url,''),
		       password_hash, created_at, updated_at
		FROM profiles
		WHERE id = $1`

	p := &domain.Profile{}
	err := r.db.QueryRow(ctx, query, id).Scan(
		&p.ID, &p.Name, &p.Email, &p.Phone, &p.Role,
		&p.TotalPoints, &p.AddressDefault, &p.AvatarURL,
		&p.PasswordHash, &p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("get profile by id: %w", err)
	}
	return p, nil
}

// EmailExists checks whether an email is already registered
func (r *AuthRepository) EmailExists(ctx context.Context, email string) (bool, error) {
	var exists bool
	err := r.db.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM profiles WHERE email=$1)`, email).Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("check email exists: %w", err)
	}
	return exists, nil
}

// ListProfilesByRole returns all profiles with specific role
func (r *AuthRepository) ListProfilesByRole(ctx context.Context, role string) ([]domain.Profile, error) {
	query := `
		SELECT id, name, email, COALESCE(phone,''), role, total_points,
		       COALESCE(address_default,''), COALESCE(avatar_url,''),
		       password_hash, created_at, updated_at
		FROM profiles
		WHERE role = $1
		ORDER BY created_at DESC`

	rows, err := r.db.Query(ctx, query, role)
	if err != nil {
		return nil, fmt.Errorf("list profiles by role: %w", err)
	}
	defer rows.Close()

	var profiles []domain.Profile
	for rows.Next() {
		var p domain.Profile
		if err := rows.Scan(
			&p.ID, &p.Name, &p.Email, &p.Phone, &p.Role,
			&p.TotalPoints, &p.AddressDefault, &p.AvatarURL,
			&p.PasswordHash, &p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan profile: %w", err)
		}
		profiles = append(profiles, p)
	}

	return profiles, rows.Err()
}

// CountProfilesByRole counts profiles with specific role
func (r *AuthRepository) CountProfilesByRole(ctx context.Context, role string) (int, error) {
	var count int
	err := r.db.QueryRow(ctx, `SELECT COUNT(*) FROM profiles WHERE role = $1`, role).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count profiles by role: %w", err)
	}
	return count, nil
}

// GetTotalPoints returns sum of all user points
func (r *AuthRepository) GetTotalPoints(ctx context.Context) (int, error) {
	var total int
	err := r.db.QueryRow(ctx, `SELECT COALESCE(SUM(total_points), 0) FROM profiles`).Scan(&total)
	if err != nil {
		return 0, fmt.Errorf("get total points: %w", err)
	}
	return total, nil
}

// DeleteProfile deletes a profile
func (r *AuthRepository) DeleteProfile(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM profiles WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("delete profile: %w", err)
	}
	return nil
}