package repository

import (
	"context"
	"errors"
	"fmt"

	"ecotracker/internal/domain"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type PickupRepository struct {
	db *pgxpool.Pool
}

func NewPickupRepository(db *pgxpool.Pool) *PickupRepository {
	return &PickupRepository{db: db}
}

// scanPickup scans a full pickup row
func scanPickup(row pgx.Row) (*domain.Pickup, error) {
	p := &domain.Pickup{}
	err := row.Scan(
		&p.ID, &p.UserID, &p.CollectorID, &p.Status,
		&p.Address, &p.Latitude, &p.Longitude,
		&p.PhotoURL, &p.Notes, &p.CompletedAt, &p.CreatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("scan pickup: %w", err)
	}
	return p, nil
}

// Create inserts a new pickup (UUID generated by DB)
func (r *PickupRepository) Create(ctx context.Context, p *domain.Pickup) error {
	query := `
		INSERT INTO pickups (id, user_id, status, address, latitude, longitude, photo_url, notes, created_at)
		VALUES (gen_random_uuid(), $1, 'pending', $2, $3, $4, $5, $6, NOW() AT TIME ZONE 'Asia/Jakarta')
		RETURNING id, COALESCE(collector_id::text,''), status, created_at`

	err := r.db.QueryRow(ctx, query,
		p.UserID, p.Address, p.Latitude, p.Longitude, p.PhotoURL, p.Notes,
	).Scan(&p.ID, &p.CollectorID, &p.Status, &p.CreatedAt)
	if err != nil {
		return fmt.Errorf("create pickup: %w", err)
	}
	return nil
}

// GetByID fetches a single pickup by its UUID
func (r *PickupRepository) GetByID(ctx context.Context, id string) (*domain.Pickup, error) {
	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at
		FROM pickups WHERE id=$1`

	return scanPickup(r.db.QueryRow(ctx, query, id))
}

// ListByUserID returns all pickups requested by a user (UUID)
func (r *PickupRepository) ListByUserID(ctx context.Context, userID string) ([]domain.Pickup, error) {
	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at
		FROM pickups WHERE user_id=$1 ORDER BY created_at DESC`

	rows, err := r.db.Query(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("list pickups by user: %w", err)
	}
	defer rows.Close()

	return scanPickupRows(rows)
}

// ListByStatus returns all pickups with a given status (for collector dashboard)
func (r *PickupRepository) ListByStatus(ctx context.Context, status string) ([]domain.Pickup, error) {
	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at
		FROM pickups WHERE status=$1 ORDER BY created_at ASC`

	rows, err := r.db.Query(ctx, query, status)
	if err != nil {
		return nil, fmt.Errorf("list pickups by status: %w", err)
	}
	defer rows.Close()

	return scanPickupRows(rows)
}

// ListByCollectorID returns pickups assigned to a specific collector
func (r *PickupRepository) ListByCollectorID(ctx context.Context, collectorID string) ([]domain.Pickup, error) {
	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at
		FROM pickups WHERE collector_id=$1 ORDER BY created_at DESC`

	rows, err := r.db.Query(ctx, query, collectorID)
	if err != nil {
		return nil, fmt.Errorf("list pickups by collector: %w", err)
	}
	defer rows.Close()

	return scanPickupRows(rows)
}

// TakeTask assigns a collector to a pending pickup (status: pending → taken)
func (r *PickupRepository) TakeTask(ctx context.Context, pickupID, collectorID string) error {
	query := `
		UPDATE pickups
		SET collector_id=$1, status='taken'
		WHERE id=$2 AND status='pending'`

	result, err := r.db.Exec(ctx, query, collectorID, pickupID)
	if err != nil {
		return fmt.Errorf("take task: %w", err)
	}
	if result.RowsAffected() == 0 {
		return domain.ErrPickupAlreadyTaken
	}
	return nil
}

// CompletePickupTx executes the atomic completion workflow inside a transaction.
// Steps: update pickup → insert items → update points → log transaction
func (r *PickupRepository) CompletePickupTx(
	ctx context.Context,
	pickupID, collectorID string,
	items []domain.PickupItem,
	totalPoints int,
	userID string,
) error {
	tx, err := r.db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback(ctx)
		}
	}()

	// Step 1: Update pickup status to completed
	updatePickup := `
		UPDATE pickups
		SET status='completed', collector_id=$1, completed_at=NOW()
		WHERE id=$2 AND status='taken' AND collector_id=$1`
	result, err := tx.Exec(ctx, updatePickup, collectorID, pickupID)
	if err != nil {
		return fmt.Errorf("complete pickup update: %w", err)
	}
	if result.RowsAffected() == 0 {
		return domain.ErrPickupNotTaken
	}

	// Step 2: Insert pickup items
	for _, item := range items {
		_, err = tx.Exec(ctx,
			`INSERT INTO pickup_items (pickup_id, category_id, weight, subtotal_points) VALUES ($1,$2,$3,$4)`,
			pickupID, item.CategoryID, item.Weight, item.SubtotalPoints,
		)
		if err != nil {
			return fmt.Errorf("insert pickup item (category %d): %w", item.CategoryID, err)
		}
	}

	// Step 3: Add points to user's profile
	_, err = tx.Exec(ctx,
		`UPDATE profiles SET total_points = total_points + $1 WHERE id = $2`,
		totalPoints, userID,
	)
	if err != nil {
		return fmt.Errorf("update user points: %w", err)
	}

	// Step 4: Log the point transaction
	_, err = tx.Exec(ctx,
		`INSERT INTO point_logs (user_id, amount, transaction_type, reference_id, description)
		 VALUES ($1, $2, 'earning', $3, 'Points earned from waste pickup')`,
		userID, totalPoints, pickupID,
	)
	if err != nil {
		return fmt.Errorf("insert point log: %w", err)
	}

	if err = tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit transaction: %w", err)
	}
	return nil
}

// GetItemsByPickupID retrieves all items for a given pickup
func (r *PickupRepository) GetItemsByPickupID(ctx context.Context, pickupID string) ([]domain.PickupItem, error) {
	rows, err := r.db.Query(ctx,
		`SELECT id, pickup_id, category_id, weight, subtotal_points FROM pickup_items WHERE pickup_id=$1`,
		pickupID,
	)
	if err != nil {
		return nil, fmt.Errorf("get pickup items: %w", err)
	}
	defer rows.Close()

	var items []domain.PickupItem
	for rows.Next() {
		var item domain.PickupItem
		if err := rows.Scan(&item.ID, &item.PickupID, &item.CategoryID, &item.Weight, &item.SubtotalPoints); err != nil {
			return nil, fmt.Errorf("scan pickup item: %w", err)
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

func scanPickupRows(rows pgx.Rows) ([]domain.Pickup, error) {
	var pickups []domain.Pickup
	for rows.Next() {
		var p domain.Pickup
		err := rows.Scan(
			&p.ID, &p.UserID, &p.CollectorID, &p.Status,
			&p.Address, &p.Latitude, &p.Longitude,
			&p.PhotoURL, &p.Notes, &p.CompletedAt, &p.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan pickup row: %w", err)
		}
		pickups = append(pickups, p)
	}
	return pickups, rows.Err()
}

// ListByStatusNearLocation returns pickups sorted by distance using PostGIS
// This is the PRODUCTION version using database-level geospatial indexing
// Requires PostGIS extension and location column (see migrations/002_postgis.sql)
func (r *PickupRepository) ListByStatusNearLocation(
	ctx context.Context,
	status string,
	latitude, longitude float64,
	limit int,
) ([]domain.PickupWithDistance, error) {
	query := `
		SELECT 
			id, user_id, COALESCE(collector_id::text,''), status,
			address, latitude, longitude,
			COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at,
			ST_Distance(
				location::geography,
				ST_SetSRID(ST_MakePoint($2, $3), 4326)::geography
			) / 1000 AS distance_km
		FROM pickups
		WHERE status = $1
		ORDER BY location <-> ST_SetSRID(ST_MakePoint($2, $3), 4326)::geography
		LIMIT $4`

	rows, err := r.db.Query(ctx, query, status, longitude, latitude, limit)
	if err != nil {
		return nil, fmt.Errorf("list pickups near location (PostGIS): %w", err)
	}
	defer rows.Close()

	var pickups []domain.PickupWithDistance
	for rows.Next() {
		var pwd domain.PickupWithDistance
		err := rows.Scan(
			&pwd.ID, &pwd.UserID, &pwd.CollectorID, &pwd.Status,
			&pwd.Address, &pwd.Latitude, &pwd.Longitude,
			&pwd.PhotoURL, &pwd.Notes, &pwd.CompletedAt, &pwd.CreatedAt,
			&pwd.DistanceKm,
		)
		if err != nil {
			return nil, fmt.Errorf("scan pickup with distance: %w", err)
		}
		pickups = append(pickups, pwd)
	}

	if pickups == nil {
		pickups = []domain.PickupWithDistance{}
	}
	return pickups, rows.Err()
}

// CountByStatus counts pickups by status
func (r *PickupRepository) CountByStatus(ctx context.Context, status string) (int, error) {
	var count int
	err := r.db.QueryRow(ctx, `SELECT COUNT(*) FROM pickups WHERE status = $1`, status).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count pickups by status: %w", err)
	}
	return count, nil
}

// ListAll returns all pickups (limited to 100 for performance)
func (r *PickupRepository) ListAll(ctx context.Context) ([]domain.Pickup, error) {
	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, created_at
		FROM pickups 
		ORDER BY created_at DESC 
		LIMIT 100`

	rows, err := r.db.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("list all pickups: %w", err)
	}
	defer rows.Close()

	return scanPickupRows(rows)
}

func (r *PickupRepository) ListByStatusWithPagination(
	ctx context.Context,
	status string,
	limit int,
	offset int,
) ([]domain.Pickup, int, error) {
	var totalCount int
	countQuery := `SELECT COUNT(*) FROM pickups WHERE status = $1`
	err := r.db.QueryRow(ctx, countQuery, status).Scan(&totalCount)
	if err != nil {
		return nil, 0, fmt.Errorf("count: %w", err)
	}

	query := `
		SELECT id, user_id, COALESCE(collector_id::text,''), status,
		       address, latitude, longitude,
		       COALESCE(photo_url,''), COALESCE(notes,''), completed_at, ted_at
		FROM pickups 
		WHERE status = $1 
		ORDER BY created_at DESC
		LIMIT $2 OFFSET $3`

	rows, err := r.db.Query(ctx, query, status, limit, offset)
	if err != nil {
		return nil, 0, fmt.Errorf("query: %w", err)
	}
	defer rows.Close()

	pickups, err := scanPickupRows(rows)
	return pickups, totalCount, err
}